# 1.Specify the compose file format; we're using the last one.
#   If you're curious, at https://docs.docker.com/compose/compose-file/compose-versioning/
#   you can find an extensive description on the difference among versions
version: '3'
# 2.Specify the list of services that will be built. In our case, app (Ruby on Rails) and web (NGINX)
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build:
      # 2.1.Specify the root path
      context: .
      # 2.2.From the root path defined in context, here we define where the Dockerfile resides
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # 2.4.Binds port 80 for public connections
    links:
      - app
    ports:
      - 80:80
