default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: assignment_dev

test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: assignment_test

production:
  <<: *default
  host: localhost
  port: 5432
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  database: assignment