default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: assignment_dev

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: assignment_test

production:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: assignment